import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "../../components/modules/footer";
import Scroller from "../../components/modules/scroller";
import ReactQueryProvider from "@/utils/reactQuery";

export const metadata = {
  title: "MAS CHAT",
  description: "Generated by create next app",
  favicon: "../../public/images/logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {children}
          <Footer />
          <Scroller />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
