import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Footer from "../../components/modules/footer";
import MyContextProvider from "../../utils/contextProvider";
import Scroller from "../../components/modules/scroller";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyContextProvider>
      <html lang="en">
        <body>
          {children}
          <Footer />
          <Scroller/>
        </body>
      </html>
    </MyContextProvider>
  );
}
